### PR TITLE
Updated NYC intersection records

### LINKED ISSUE #1: Clip existing intersection features to the polygon of Manhattan
Existing intersection records in Manhattan have geometries that extend far beyond the boundary of Manhattan. Instead of being clipped to the polygon of their parent locality, these records' geometries were clipped to the bounding box of Manhattan.

This will cause issues down the road when adding or updating venues in New York and New Jersey.

For features that have geometries extending outside the polygon of NYC, update default geometries and store existing geometries as alt-geoms... or ditch them altogether.

**Screenshot via descender tool:**

screen shot 2017-05-25 at 12 03 59 pm

### PR DESCRIPTION
**Pull request by stepps00**
Picking up where #2 left off, fixes #1...

This PR updates NYC intersection records that have oversized polygon geometries extending into neighboring boroughs and New Jersey. The original geometries were stored as alt geometries, and the default geometries were clipped to the boundary of Manhattan.

Step 1:  **Clip all features to the boundary of Manhattan**
screen shot 2017-05-26 at 12 10 32 pm

Step 2: **Select features at the perimeter of Manhattan for updates**
screen shot 2017-05-26 at 12 15 32 pm

Only features touching the perimeter of Manhattan were updated, since the inner polygons were unchanged. 

Latitude and longitude properties were updated to fall within the new geometry shape.

### CODE REVIEW

**Comment by thisisaaronland** [comment]
What are all those "alt" geometries? How can intersections already have alternates?

**Comment by nvkelso** [comment]
I'm fine removing the alt geoms from this PR. We've generally been keeping alt geoms around even if they were funky (e.g. for quattroshapes neighbourhood polygons), but since these were recently added and they're from us let's remove them.

**Comment by nvkelso** [comment]
@stepps00 what's the difference between the earlier PR and this one?

**Comment by stepps00** [comment]
@nvkelso - the last branch had some funky `misc` properties that snuck past me. I'll update this PR to remove the alt geoms and pointers shortly.

**Comment by stepps00** [comment]
@thisisaaronland - most recent commit removes alt geometry files and any `src:geom_alt` property updates. This PR should be ready to merge.

**Review by thisisaaronland — APPROVED** [review]

**Pull request merged**
